name: cicd-action

on: 
# manual click(deliver) when user needs
  workflow_dispatch:
    inputs:
      environment:
        description: This is environment where this workflows 
        default: 'dev'
        required: true
        type: choice
        options:
          - 'dev'
          - 'prod'
          - 'stagging'
       
    

jobs:
#every jobs needs a seperate runner,its called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: code of app
        run : echo "git checkout"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:  
      - name: build the code by container
        run: echo "docker build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "testing code"
  deploy:
    
    needs: [test,build,code]
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        run: echo "docker compose build code"
